name: ar_thunderstorm
channels:
  - conda-forge
  - defaults  
dependencies:
  - python=3.7
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - netcdf4
  - xarray
  - dask
  - bottleneck
  - cartopy
  - seaborn
  - cmocean
  - metpy
  - ipykernel
  - jupyter
  - geopandas
  - wrf-python
  - zarr
  
  - pip:
    - descartes
    - boto3
    - botocore
    - shapely
    - fiona